### ISSUE TITLE
Incorrect/Out-of-Date Package

### ISSUE THREAD

**Issue by TheKevJames** [conda-forge/coveralls-feedstock#2]
@conda-forge/core Hi there! I am the maintainer of this project ever since it was moved from https://github.com/coagulant/coveralls-python to https://github.com/coveralls-clients/coveralls-python

I notice some of the details in this feedstock are incorrect/out-of-date (the repo url has moved, the latest release is 1.2.0 but recorded here as 1.1, etc). I'm very new to conda and I see you do much of this sort of stuff automatically -- how should I/we go about fixing this?

Should I open a PR against `recipe/meta.yaml`? Will I need to do this for each new release?

**Comment by ocefpaf** [comment]
> Should I open a PR against `recipe/meta.yaml`?

That would be awesome. (And consider adding yourself as a maintainer too.)

> Will I need to do this for each new release?

At the moment yes, but we are looking into ways to automate PyPI updates.
